name: AliveWater Monitoring

on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium python-telegram-bot==20.3 webdriver-manager
        
    - name: Setup Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        # Проверяем существование ссылки перед созданием
        [ ! -f "/usr/bin/google-chrome" ] && sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome || true
        
    - name: Run monitoring
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python alivewater_monitor.py
